//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintSample {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringLibrary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringLibrary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrintSample.StringLibrary", typeof(StringLibrary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select BT Connect.
        /// </summary>
        internal static string BT_CONNECT {
            get {
                return ResourceManager.GetString("BT_CONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms-settings-bluetooth:.
        /// </summary>
        internal static string BT_SETTINGS {
            get {
                return ResourceManager.GetString("BT_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to Printer....
        /// </summary>
        internal static string CONNECT_STATUS {
            get {
                return ResourceManager.GetString("CONNECT_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to printer successfully.
        /// </summary>
        internal static string CONNECT_SUCCESS {
            get {
                return ResourceManager.GetString("CONNECT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnecting to Printer....
        /// </summary>
        internal static string DISCONNECT_STATUS {
            get {
                return ResourceManager.GetString("DISCONNECT_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected to printer successfully.
        /// </summary>
        internal static string DISCONNECT_SUCCESS {
            get {
                return ResourceManager.GetString("DISCONNECT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Parameter.
        /// </summary>
        internal static string ERR_INVALID_PARAM {
            get {
                return ResourceManager.GetString("ERR_INVALID_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .json file not found.
        /// </summary>
        internal static string ERR_JSON_FILE {
            get {
                return ResourceManager.GetString("ERR_JSON_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to does not support label printing.
        /// </summary>
        internal static string ERR_LBL_PRINT {
            get {
                return ResourceManager.GetString("ERR_LBL_PRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Mac Address.
        /// </summary>
        internal static string ERR_MAC_ADDR {
            get {
                return ResourceManager.GetString("ERR_MAC_ADDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Printer ID.
        /// </summary>
        internal static string ERR_PRNTR_ID {
            get {
                return ResourceManager.GetString("ERR_PRNTR_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fingerprint.
        /// </summary>
        internal static string FP {
            get {
                return ResourceManager.GetString("FP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid error.
        /// </summary>
        internal static string INVALID_ERR {
            get {
                return ResourceManager.GetString("INVALID_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to printer_profiles.JSON.
        /// </summary>
        internal static string JSON_FILE {
            get {
                return ResourceManager.GetString("JSON_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in Printing Label,check connection.
        /// </summary>
        internal static string LBL_ERROR_STATUS {
            get {
                return ResourceManager.GetString("LBL_ERROR_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing Label ....
        /// </summary>
        internal static string LBL_PRINT_STATUS {
            get {
                return ResourceManager.GetString("LBL_PRINT_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printed Label Succeessfully.
        /// </summary>
        internal static string LBL_PRINT_SUCCESS {
            get {
                return ResourceManager.GetString("LBL_PRINT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrintLabel.
        /// </summary>
        internal static string LBL_TITLE {
            get {
                return ResourceManager.GetString("LBL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in Printing Receipt,check connection.
        /// </summary>
        internal static string RECPT_ERROR_STATUS {
            get {
                return ResourceManager.GetString("RECPT_ERROR_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing Receipt ....
        /// </summary>
        internal static string RECPT_PRINT_STATUS {
            get {
                return ResourceManager.GetString("RECPT_PRINT_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printed Receipt Succeessfully.
        /// </summary>
        internal static string RECPT_PRINT_SUCCESS {
            get {
                return ResourceManager.GetString("RECPT_PRINT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrintReciept.
        /// </summary>
        internal static string RECPT_TITLE {
            get {
                return ResourceManager.GetString("RECPT_TITLE", resourceCulture);
            }
        }
    }
}
